import re
from datetime import datetime, timedelta, timezone
from email.utils import format_datetime
from pathlib import Path

import requests
from bs4 import BeautifulSoup


def run():
    urls = [
        "https://thehimalayantimes.com/morearticles/World",
        "https://thehimalayantimes.com/morearticles/Nepal",
        "https://thehimalayantimes.com/morearticles/Kathmandu",
    ]

    rss_gen("world", urls[0])
    rss_gen("nepal", urls[1])
    rss_gen("kathmandu", urls[2])


def fetch_articles(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
    r = requests.get(url, headers=headers, timeout=30)
    soup = BeautifulSoup(r.text, "html.parser")

    newsblocks = soup.find_all(
        "div", class_="col-md-9 animate-box fadeInUp animated-fast"
    )

    articles = []
    for nb in newsblocks:
        h = nb.find("h3", class_="alith_post_title HideMobile")
        a = h.find("a", href=True)
        p = nb.find("div", class_="alith_post_except HideMobile fontsize14height40")
        d = nb.find("span", class_="meta_date")

        headline = h.get_text(strip=True)
        preview = p.get_text(strip=True)
        date = d.get_text(strip=True)
        link = a.get("href")
        articles.append(
            {"headline": headline, "link": link, "description": preview, "date": date}
        )
    return articles


def parse_date(s):
    TZ = timezone.utc
    s = s.strip()

    # "3h ago"
    m = re.fullmatch(r"(\d+)\s*h\s*ago", s, flags=re.I)
    if m:
        hours = int(m.group(1))
        return datetime.now(TZ) - timedelta(hours=hours)

    # "2d ago"
    m = re.fullmatch(r"(\d+)\s*d\s*ago", s, flags=re.I)
    if m:
        days = int(m.group(1))
        return datetime.now(TZ) - timedelta(days=days)

    # "29 Jun, 2026" or "29 Jun 2026"
    for fmt in ("%d %b, %Y", "%d %b %Y"):
        try:
            dt = datetime.strptime(s, fmt)
            return dt.replace(tzinfo=TZ)
        except ValueError:
            pass

    return datetime.now(TZ)


def rss_gen(section, url):
    articles = fetch_articles(url)
    rss_title = f"{section} - The Himalayan Times - Nepal's No.1 English Daily Newspaper | Nepal News, Latest Politics, Business, World, Sports, Entertainment, Travel, Life Style News"
    out_file = f"{Path.home()}/.config/newsboat/himalayantimes{section}.rss.xml"

    with open(out_file, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<rss version="2.0">\n')
        f.write("   <channel>\n")
        f.write(f"      <title>{rss_title}</title>\n")
        f.write(f"      <link>{url}</link>\n")
        f.write(
            "      <description>Personal Feed Generated by Scraping.</description>\n"
        )

        for article in articles:
            headline = (
                article["headline"]
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            link = article["link"]
            description = (
                article["description"]
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            date = parse_date(article["date"])
            guid = link

            f.write("       <item>\n")
            f.write(f"          <title>{headline}</title>\n")
            f.write(f"          <link>{link}</link>\n")
            f.write(f'          <guid isPermaLink="true">{guid}</guid>\n')
            f.write(f"          <description>{description}</description>\n")
            f.write(
                f"          <pubDate>{format_datetime(date, usegmt=True)}</pubDate>\n"
            )
            f.write("       </item>\n")

        f.write("   </channel>\n")
        f.write("</rss>\n")

    print("Wrote:", out_file)


if __name__ == "__main__":
    run()
