import re
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path

import requests
from bs4 import BeautifulSoup


def run():
    urls = [
        "https://kathmandupost.com/politics",
        "https://kathmandupost.com/national",
        "https://kathmandupost.com/valley",
    ]
    rss_gen("politics", urls[0])
    rss_gen("national", urls[1])
    rss_gen("valley", urls[2])


def fetch_date(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
    r = requests.get(url, headers=headers, timeout=30)
    soup = BeautifulSoup(r.text, "html.parser")

    t = soup.find("div", class_="updated-time")
    m = re.search(r"([A-Za-z]+\s+\d{1,2},\s+\d{4})", t.get_text(" ", strip=True))
    return m.group(1)


def fetch_articles(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
    r = requests.get(url, headers=headers, timeout=30)
    soup = BeautifulSoup(r.text, "html.parser")

    div = soup.find("div", class_="block--morenews")
    newsblocks = div.find_all("article", class_="article-image")

    articles = []
    for nb in newsblocks:
        img_div = nb.select_one("div.image.image-sm")
        if img_div:
            img_div.decompose()

        a = nb.find("a")
        h = a.find("h3")
        p = nb.find("p")

        headline = h.get_text(strip=True)
        preview = p.get_text(strip=True)
        link = f"https://kathmandupost.com{a.get('href')}"
        date = fetch_date(link)

        articles.append(
            {"headline": headline, "link": link, "description": preview, "date": date}
        )
    return articles


def parse_date(s):
    # June 29, 2026
    TZ = timezone.utc
    s = (s or "").strip()

    m = re.fullmatch(r"([A-Za-z]+)\s+(\d{1,2}),\s+(\d{4})", s)
    if not m:
        return datetime.now(TZ)

    month_str, day_str, year_str = m.groups()
    dt = datetime.strptime(f"{month_str} {day_str} {year_str}", "%B %d %Y")
    return dt.replace(tzinfo=TZ)


def rss_gen(section, url):
    articles = fetch_articles(url)
    rss_title = f"{section} - The Kathmandu Post"
    out_file = f"{Path.home()}/.config/newsboat/kathmandupost{section}.rss.xml"

    with open(out_file, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<rss version="2.0">\n')
        f.write("   <channel>\n")
        f.write(f"      <title>{rss_title}</title>\n")
        f.write(f"      <link>{url}</link>\n")
        f.write(
            "      <description>Personal Feed Generated by Scraping.</description>\n"
        )

        for article in articles:
            headline = (
                article["headline"]
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            link = article["link"]
            description = (
                article["description"]
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            date = parse_date(article["date"])
            guid = link

            f.write("       <item>\n")
            f.write(f"          <title>{headline}</title>\n")
            f.write(f"          <link>{link}</link>\n")
            f.write(f'          <guid isPermaLink="true">{guid}</guid>\n')
            f.write(f"          <description>{description}</description>\n")
            f.write(
                f"          <pubDate>{format_datetime(date, usegmt=True)}</pubDate>\n"
            )
            f.write("       </item>\n")

        f.write("   </channel>\n")
        f.write("</rss>\n")

    print("Wrote:", out_file)


if __name__ == "__main__":
    run()
